# Generated by Django 4.2.8 on 2024-01-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baseclientmodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(default=None, max_length=254)),
                ('Account', models.CharField(default=None, max_length=254)),
                ('Project_ID', models.CharField(default=None, max_length=254)),
                ('Admin', models.CharField(default=None, max_length=254)),
            ],
            options={
                'db_table': 'Baseclient',
                'ordering': ['Account', 'Admin'],
            },
        ),
    ]
