# Generated by Django 5.0.1 on 2024-01-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0002_loginmodule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginmodule',
            old_name='Account',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='loginmodule',
            old_name='Project_Name',
            new_name='Username',
        ),
    ]
