# Generated by Django 5.0.1 on 2024-01-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0003_rename_account_loginmodule_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empmodel',
            fields=[
                ('Empcode', models.CharField(default=None, max_length=254, primary_key=True, serialize=False)),
                ('EmpName', models.CharField(default=None, max_length=254)),
            ],
            options={
                'db_table': 'Emp',
            },
        ),
    ]
