# Generated by Django 4.2.9 on 2024-01-06 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0004_empmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseclientmodule',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TimeSheet.empmodel'),
        ),
        migrations.AddField(
            model_name='loginmodule',
            name='Login_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TimeSheet.empmodel'),
        ),
    ]
