# Generated by Django 4.2.9 on 2024-01-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0005_baseclientmodule_client_id_loginmodule_login_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseclientmodule',
            options={'ordering': ['Client_Id', 'Admin_Id']},
        ),
        migrations.RenameField(
            model_name='baseclientmodule',
            old_name='Account',
            new_name='Admin_Id',
        ),
        migrations.RenameField(
            model_name='baseclientmodule',
            old_name='Project_ID',
            new_name='Client_Name',
        ),
        migrations.RenameField(
            model_name='baseclientmodule',
            old_name='Admin',
            new_name='Emp_id',
        ),
        migrations.RenameField(
            model_name='baseclientmodule',
            old_name='Project_Name',
            new_name='Task_Name',
        ),
        migrations.RenameField(
            model_name='loginmodule',
            old_name='Login_id',
            new_name='Emp_id',
        ),
    ]
