# Generated by Django 4.2.9 on 2024-01-06 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0006_alter_baseclientmodule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseclientmodule',
            options={},
        ),
        migrations.RemoveField(
            model_name='baseclientmodule',
            name='client_id',
        ),
        migrations.AlterField(
            model_name='baseclientmodule',
            name='Emp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TimeSheet.empmodel'),
        ),
        migrations.AddField(
            model_name='baseclientmodule',
            name='Client_Id',
            field=models.CharField(default=None, max_length=254),
        ),
    ]
