# Generated by Django 4.2.9 on 2024-01-07 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0007_alter_baseclientmodule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empattendancemodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField(default=None, max_length=254)),
                ('Client_Name', models.CharField(default=None, max_length=254)),
                ('Client_Id', models.CharField(default=None, max_length=254)),
                ('Task_Name', models.CharField(default=None, max_length=254)),
                ('HOURS', models.CharField(default=None, max_length=254)),
                ('Emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TimeSheet.empmodel')),
            ],
        ),
    ]
