# Generated by Django 4.2.9 on 2024-01-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0011_empattendancemodule_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empattendancemodule',
            name='Emp_id',
        ),
        migrations.AlterModelTable(
            name='empattendancemodule',
            table='Empattendance',
        ),
    ]
