# Generated by Django 4.2.9 on 2024-01-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0012_remove_empattendancemodule_emp_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empattendancemodule',
            name='Task_Name',
        ),
        migrations.AddField(
            model_name='empattendancemodule',
            name='Task',
            field=models.CharField(choices=[('B', 'Billable'), ('A', 'Admin'), ('H', 'Holiday'), ('L', 'Leave')], default=None, max_length=1),
        ),
    ]
