# Generated by Django 4.2.9 on 2024-01-10 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0013_remove_empattendancemodule_task_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseclientmodule',
            name='Task_Name',
        ),
        migrations.RemoveField(
            model_name='empattendancemodule',
            name='Client_Id',
        ),
        migrations.RemoveField(
            model_name='empattendancemodule',
            name='Client_Name',
        ),
        migrations.RemoveField(
            model_name='empattendancemodule',
            name='Task',
        ),
        migrations.AddField(
            model_name='baseclientmodule',
            name='Task',
            field=models.CharField(choices=[('B', 'Billable'), ('A', 'Admin'), ('H', 'Holiday'), ('L', 'Leave')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='empattendancemodule',
            name='Employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TimeSheet.empmodel'),
        ),
    ]
