# Generated by Django 4.2.9 on 2024-01-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0015_remove_baseclientmodule_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empattendancemodule',
            name='Task',
        ),
        migrations.AddField(
            model_name='empattendancemodule',
            name='Task_Name',
            field=models.CharField(default=None, max_length=254),
        ),
    ]
