# Generated by Django 4.2.9 on 2024-01-10 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0016_remove_empattendancemodule_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empattendancemodule',
            old_name='Employee_id',
            new_name='Emp_id',
        ),
    ]
