# Generated by Django 4.2.9 on 2024-01-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0017_rename_employee_id_empattendancemodule_emp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empmodel',
            old_name='Empcode',
            new_name='Emp_id',
        ),
    ]
