# Generated by Django 4.2.9 on 2024-01-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0018_rename_empcode_empmodel_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empattendancemodule',
            name='Emp_id',
            field=models.CharField(default=None, max_length=254),
        ),
    ]
