# Generated by Django 4.2.9 on 2024-01-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0019_alter_empattendancemodule_emp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empattendancemodule',
            old_name='Emp_id',
            new_name='Employee_id',
        ),
    ]
